---
# file: roles/common/restart/tasks/main.yml

- name: debug message
  debug:
    msg: "reboot this machine"

- name: reboot this machine
  shell: sleep 2 && shutdown -r now "Asible Updates Triggered"
  async: 5
  poll: 0
  ignore_errors: true

- name: wait for SSH port up
  wait_for:
    host: "{{ inventory_hostname }}"
    port: 22
    state: started
    delay: 30
  delegate_to: 127.0.0.1
  become: false
