---
# file: roles/common/setup/tasks/main.yml

- name: initialize setup repository epel
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - epel-release
    - "http://rpms.remirepo.net/enterprise/remi-release-7.rpm"

- name: disable selinux
  selinux:
#    policy: targeted
#    state: permissive
    state: disabled
  register: disable_selinux

- name: restart server
  include_role:
    name: common/restart
  when: disable_selinux|changed

- name: install ansible depend packages
  yum:
    name: "{{ item }}"
    state: latest
  with_items:
    - python-devel
    - python2-pip
    - openssl-devel
    - gcc
    - libffi-devel
    - redhat-rpm-config
